### ISSUE TITLE
rename master > main

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/CD_cwd_events_localist_pull#19]
only reason I'm waiting is so it's during the week and I can give people a heads-up + how-to :)

Speaking of which...

[How to update the branch name on your local copy of this repo](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes)

**Comment by alisonjo315** [comment]
Heads-up @ssh6!  (I already gave our team a heads-up on our Slack, just wanted to let you know, too!)

**Comment by alisonjo315** [comment]
(all done)

**Comment by ssh6** [comment]
@alisonjo315 we install this via composer ("cubear/cwd_events_localist_pull": "^1.1",) , so unless there is a new release, we won't see the changes.

**Comment by alisonjo315** [comment]
@ssh6 Oh good point, thanks for saying that, I forgot to explain:

The branch name change won't affect your use of the module, it only affects copies of the actual git repo, i.e. for people who fork or clone it to work on it. (I guess if you included the package with `dev-master` as your version constraint, it would affect use of the module, but that's less common -- and not what you're doing, obviously.)

There's no actual change to the repo code, so there won't be a release (nothing to release).

Does that make sense?

**Comment by ssh6** [comment]
@alisonjo315 it does.  I was more hoping the other merged PRs would make it into a new release... 😄

**Comment by alisonjo315** [comment]
Oh def! Once I merge this latest one, I can publish a release!

**Comment by alisonjo315** [comment]
Release published! (It's just the one change, though, there haven't been any other commits since the last release at the end of May.)
