### ISSUE TITLE
entity.query service deprecated

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/CD_cwd_events_localist_pull#22]
This deprecation wasn't called-out by upgrade_status, and it doesn't seem to affect actual importing (I'm still seeing events get imported/updated), BUT, there's a "ServiceNotFoundException" error in dblog with every cron run (and the "localist_pull" notice isn't getting logged in dblog anymore).

### Full error
> _Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException_: You have requested a non-existent service "entity.query". Did you mean one of these: "entity.query.config", "entity.query.sql", "pgsql.entity.query.sql", "entity.query.null", "entity.query.keyvalue"? in _Drupal\Component\DependencyInjection\Container->get()_ (_line 156_ of _/app/web/core/lib/Drupal/Component/DependencyInjection/Container.php_).

### Drupal core change record
[entity.query service deprecated in favor of EntityStorageInterface::getQuery()](https://www.drupal.org/node/2849874)

### Relevant line in module
https://github.com/CU-CommunityApps/CD_cwd_events_localist_pull/blob/025f31c4571199025e7ffb3e7885937dfd6086d7/cwd_events_localist_pull.module#L31

**Comment by alisonjo315** [comment]
@ssh6 Do you get the error I described, when cron runs?

**Comment by alisonjo315** [comment]
Solution MIGHT be...

```diff
@@ -28,7 +28,7 @@ function cwd_events_localist_pull_help($route_name, RouteMatchInterface $route_m
 }

 function cwd_events_localist_pull_cron() {
-    $query = \Drupal::service('entity.query')->get('localist_pull');
+    $query = \Drupal::entityQuery('localist_pull');
     $entity_ids = $query->execute();
     $config_storage = \Drupal::entityTypeManager()->getStorage('localist_pull');
     $configs = $config_storage->loadMultiple($entity_ids);
```

Or it might be something else entirely! -- **👉 check the comments on the change record for suggestions/discussion.**

**Comment by ssh6** [comment]
@alisonjo315 Yes, same error for us.  (Drupal 9.2.1, using     "cubear/cwd_events_localist_pull": "dev-drupal9")

**Comment by ssh6** [comment]
@alisonjo315 in the past when I turned on detailed cron logging, I would see the query for localist.  I'm not seeing that now, only the ServiceNotFoundException. Is that log also impacted by the bug?

**Comment by alisonjo315** [comment]
@ssh6 Great catch -- looks like I'm not getting that log message anymore either, I'll update the issue description.
