### ISSUE TITLE
Add support for "event_types"

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/CD_cwd_events_localist_pull#24]
## Preliminary specs
* Optional
* Multi- or single-value
* Data is adjacent/sibling to "departments" (`['event']['filters']['event_types']`)
* (and?)

## Decisions
1. Taxonomy term or plain text?
  * i.e. the whole vocab + term reference field setup, **_OR,_** a multi-value plain text field.
2. New field or modify existing "departments" functionality to allow departments OR event types?
3. (If new field) Provide as many config options/variations as with "departments"?
4. (and?)

## Misc notes/etc.
* Any backwards compatibility concerns?
* (and?)

**Comment by alisonjo315** [comment]
FWIW, this (very very very temporary) hack of `get_localist_event_data()` ([LocalistProcessor.php](https://github.com/CU-CommunityApps/CD_cwd_events_localist_pull/blob/main/src/LocalistProcessor.php#L114)) is working fine, so, a basic implementation of this functionality should be pretty straightforward...? --

```diff
--- a/web/modules/custom/cwd_events_localist_pull/src/LocalistProcessor.php
+++ b/web/modules/custom/cwd_events_localist_pull/src/LocalistProcessor.php
@@ -112,11 +112,11 @@ private function get_localist_event_data($event, $node_array) {
           }
           break;
         case $this->config->get('localist_tag_field_name'):
-          if(!empty($event['event']['filters']['departments']) && $event['event']['filters']['departments'] != '') {
+          if(!empty($event['event']['filters']['event_types']) && $event['event']['filters']['event_types'] != '') {
             $pull_specified_departments = $this->config->get('pull_specified_departments');
             $valid_department_array = explode(",",$this->config->get('localist_departments'));
             $department_term_array = array();
-            foreach ($event['event']['filters']['departments'] as $department_info) {
+            foreach ($event['event']['filters']['event_types'] as $department_info) {
               if($pull_specified_departments && !in_array($department_info['id'],$valid_department_array)) {
                 continue;
               }
```

**Comment by alisonjo315** [comment]
My opinions about the decisions listed in the issue description:

1. **_Personally,_** I feel like plain text is fine -- with departments, I can imagine how a vocab/taxonomy might be used on your site more than just for events, but I don't see any reason to bother with a vocab...
  * Then again, I guess a vocab would make it easier to have exposed view filters by event type...
2. Probably just a new field.
3. Nah.  Well, if it's a vocab integration, we'll still need those three checkboxes under the "Department Taxonomy" heading...
  * But, no need for `pull_specified_departments` ("Should we pull only the specified departments as tags?")

**Comment by alisonjo315** [comment]
@judaw If you don't have time to read this, 100% ok, just figured I'd throw it at you and if you have time, cool!

----
"Make it configurable" -- that's certainly the dream.  Here's a brainstorm-y dump from my brain when I think of how it could be "configurable" -- lmk what you think, or what other ideas you have:
1. Modify existing "departments" functionality to allow departments OR event types -- or to allow you to pick one or more metadata-y fields that come in from localist?
2. Leave "departments" alone, and add a new section of localist_pull entity config, where you can pick one or more metadata-y fields that come in from localist, and map them to one or more fields on your event ctype? (...and the other settings currently available for departments -- so it would be like 3-4 settings per metadata field -- or would there be fewer options...?)
3. ...?

**Comment by ssh6** [comment]
@alisonjo315 So I've "hacked" things in the past by adding my own filters on the URL field.  (https://events.cornell.edu/api/2/events?api_key=KLhy2GtuSAGirYGY**&distinct=true** for example).  Perhaps instead of trying to account for every possibility, there is an "advanced" field or something that just lets you specify the exact config you want in the URL field.  It would let us more advanced people do what we need to, since 95% of the users of this module will be trained drupal developers/admins.

**Comment by alisonjo315** [comment]
@ssh6 I like that Idea -- when I was writing my previous comment, I had a third idea to allow for entering text that would be for a JSON field, it just felt like, mmmmpotentially break-y :)  But it's totally worth considering.  Thanks for the input!!!!

**Comment by alisonjo315** [comment]
"Nice to have" fields list suggested by Phil on Slack:
```
Title
Description
Start Date
End Date
Start Time
End Time
Location
Address
Room Number
URL
Event Types
Keywords
Tags
Photo URL
Ticket URL
Cost
Hashtag
Facebook URL
Group
Department
Allows Reviews
Visibility
Featured
Sponsored
Venue Page Only
```

**Comment by alisonjo315** [comment]
PR #30 is ready for review; also fixes [notices bug](https://github.com/CU-CommunityApps/CD_cwd_events_localist_pull/issues/31).

It doesn't do everything we want, but I think it's ok for a start.

Normally I'd put conversation over on the PR, but for whatever reason, I'm feeling like putting "what should this functionality include/not include" thoughts in the issue thread, so here we are:
* I do like the idea of offering a highly flexible "you provide whatever machine names you need" option, BUT, as I thought about it, it seems like it would need to be two of these flexible fields:
  * one that maps into a text field
  * one that maps into a taxonomy reference field (b/c it has to have term lookup/creation capabilities)
* There's probably another way to do it, but "time" blah blah blah, this is what I came up with.  Suggestions are welcome!
* If [#30](https://github.com/CU-CommunityApps/CD_cwd_events_localist_pull/pull/30) is approved/merged with the event types support pretty much the way I built it, I'll create a follow-up issue to work on some options for flexible fields.
