### ISSUE TITLE
D9 config_export: Modifying localist pull drupal config generates error

### ISSUE THREAD

**Issue by ssh6** [CU-CommunityApps/CD_cwd_events_localist_pull#26]
### Error upon saving localist entity
> Drupal\Core\Config\Schema\SchemaIncompleteException: Entity type 'Drupal\cwd_events_localist_pull\Entity\LocalistConfig' is missing 'config_export' definition in its annotation in Drupal\Core\Config\Entity\ConfigEntityBase->toArray() (line 252 of /mnt/www/html/cornellssitd9dev/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php).

### Message from upgrade status report
> Configuration entity must define a `config_export` key. See https://www.drupal.org/node/2481909

### Relevant annotation
_(annotation = fancy docblock)_
https://github.com/CU-CommunityApps/CD_cwd_events_localist_pull/blob/main/src/Entity/LocalistConfig.php#L10

**Comment by ssh6** [comment]
error generated when I tried to modify the CD_cwd_events_localist_pull config and save it.

**Comment by ssh6** [comment]
Searching for '"config_export" definition drupal 9' in google produces a number of modules that have needed to be remediated because of this error.

**Comment by alisonjo315** [comment]
Thank you for the report, @ssh6!  I can't promise any definitive timing, but we'll look at it ASAP, along with #22.

**Comment by ssh6** [comment]
@alisonjo315 Thanks!  We are holding off on a D9 conversion go-live until this module is remediated.  Since I can't modify config to test anything, I'm concerned it has more systemic issues that we can't yet identify through more robust QA.

**Comment by alisonjo315** [comment]
(note to self: [upgrade_status added this check a few days ago](https://www.drupal.org/project/upgrade_status/issues/3161052), so that's super helpful! -- and the error links to the issue Sean shared in the issue description, see screenshot below)

![image](https://user-images.githubusercontent.com/2660348/126845265-efad492a-e112-4e88-a1fb-eb042af7799f.png)
