### ISSUE TITLE
[META] Drupal 9 compatible release

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/CD_cwd_events_localist_pull#29]
Blockers:
- [x] #15 
- [x] #22 
- [x] #26

**Comment by ssh6** [comment]
@alisonjo315 Are you expecting a new tagged release to go with the d9 compatibility?

**Comment by alisonjo315** [comment]
Yeppers! Just published:
https://github.com/CU-CommunityApps/CD_cwd_events_localist_pull/releases/tag/2.0.1

**Comment by alisonjo315** [comment]
@ssh6 Things going ok so far, with 2.0.1 on Drupal 9? 🤞

**Comment by ssh6** [comment]
@alisonjo315 We launched our first D9 site in prod on Thursday last week.  So far, so good!

**Comment by alisonjo315** [comment]
That's AWESOME news, thank you!
