### ISSUE TITLE
file_prepare_directory is deprecated

### ISSUE THREAD

**Issue by philwilliammee** [CU-CommunityApps/CD_cwd_events_localist_pull#3]
in https://github.com/CU-CommunityApps/CD_cwd_events_localist_pull/blob/master/src/LocalistProcessor.php

file_prepare_directory @deprecated in
Drupal 8.7.0, will be removed before Drupal 9.0.0. Use \Drupal\Core\File\FileSystemInterface::prepareDirectory().

replace lines 128-140 with
```php
private function create_file_and_array($url) {
  $temp        = explode('/', $url);
  $photo_name  = array_pop($temp);
  $data        = file_get_contents($url);
  $path        = 'public://localist';
  $destination = "$path/$photo_name";
  \Drupal::service('file_system')->prepareDirectory(
    $path,
    FileSystemInterface::CREATE_DIRECTORY
  );
  $file = file_save_data($data, $destination, FileSystemInterface::EXISTS_REPLACE);
  $photo_array = [
    'target_id' => $file->id(),
    'alt' => '',
  ];
  return $photo_array;
}
```

If I have time I'll do a pull request and testing.

this may also require  $settings['file_temp_path'] = '/tmp'; https://www.drupal.org/node/3039255

**Comment by alisonjo315** [comment]
Closing in favor of #15 

@philwilliammee if you have time/interest, you could look at Eric's handling of this specific function deprecation, in PR #16. (Only if you have time/interest!)
