### ISSUE TITLE
Multiple localist feeds

### ISSUE THREAD

**Issue by ssh6** [CU-CommunityApps/CD_cwd_events_localist_pull#36]
With a large site, having a single localist pull might be problematic.  Would be useful to allow multiple feeds for a variety of reasons.

**Comment by alisonjo315** [comment]
@ssh6 I can add multiple localist pull feeds to sites -- could you clarify what you're not able to do?

(on /admin/config/system/localist_pull > "Add Localist Pull entity")
![image](https://user-images.githubusercontent.com/2660348/155254733-ee225fdc-41fe-4913-89eb-989ecd9c606a.png)

**Comment by ssh6** [comment]
@alisonjo315 Well look at that!

Helps if I actually look where it obviously would be.

**Comment by alisonjo315** [comment]
Yay!  Happy I could help with an simple answer ⭐
