### ISSUE TITLE
Count doesn't go above 100

### ISSUE THREAD

**Issue by ssh6** [CU-CommunityApps/CD_cwd_events_localist_pull#37]
Presently in the UI, we can set count to be greater than 100.  However, per the API, only 100 can be returned *per page*.  It doesn't appear that the generated url is paging the results.  (We should be specifying page=1,page=2 if the results returned are greater than 100). The default for no page specified is 1 (forcing a max of 100)

https://developer.localist.com/doc/api#paging-json

(note the "pp=100&page=2")

"https://events.cornell.edu/api/2/events?api_key=KLhy2GtuSAGirYGY&distinct=true&days=370&sort=date&type[]=37623703782130&type[]=4184&type[]=45850&type[]=42308&type[]=85641&type[]=85642&type[]=4201&type[]=4203&type[]=42683&type[]=14433&type[]=17608&type[]=118100&type[]=142642&type[]=48196&type[]=90450&type[]=107112&type[]=14871&type[]=4196&type[]=112710&type[]=28848&type[]=29435&type[]=79107&type[]=10445&type[]=4202&type[]=6002&type[]=5146&type[]=14872&type[]=5061&type[]=42309&type[]=4230&type[]=42310&type[]=25361&type[]=112709&type[]=107549&type[]=4236&type[]=42311&type[]=4237&type[]=4246&type[]=25360&pp=100&page=2&start=2022-02-09"

@cll6

**Comment by philwilliammee** [comment]
for use cases like this it may be better to integrate directly with the localist api like we do in https://github.com/CU-CommunityApps/CD_cwd_events and use the [calendar ](https://philwilliammee.github.io/react-localist-viewer/?path=/story/react-localist-viewer-localist-app--calendar) or one of the [paginated list ](https://philwilliammee.github.io/react-localist-viewer/?path=/story/react-localist-viewer-localist-app--standard&args=entries:5) view options.

**Comment by philwilliammee** [comment]
just as a note the calendar view can only show a max of 100 events per month, the paginated view can handle unlimited.

**Comment by ssh6** [comment]
@philwilliammee So you are saying we should abandon CD_cwd_events_localist_pull and build it ourselves?

**Comment by judaw** [comment]
@ssh6 I am sure there would be a way to update the module to handle when you are pulling more than 100 events to a site. To me my quick look at the API documentation it looks like it pages the results. The module would need to be updated to parse through more than one page of results. Would definitely make sense to add this feature to the module. Been working exclusively on Daily Check so have not had time to look in more detail.

**Comment by philwilliammee** [comment]
Its up to the end requirements. If it is required that the events are created/modified/stored in the Drupal database than the option I posted above is not helpful. If the Drupal site is only mirroring what is on cornell events calendar. Than it may be quicker to use our prebuilt Drupal integration than modify the events pull. 

just posting it as an option. I guess it doesn't really belong in this issue, as its really unrelated.

**Comment by inaydich** [comment]
@ssh6 Ryann is back next week and I can ask her to schedule this work for whatever decision you make - either update the  existing module or switch to another event module that does not import the events. The latter solution (integration without import) would work if you do not add your own events locally and only mirroring the Cornell events.

**Comment by cll6** [comment]
I've become aware that some events are not showing up on our site (scl.cornell.edu).  I looked at the error messages and see "InvalidArgumentException: Field field_event_description is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of /mnt/www/html/cornellssitd9/docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php)."
02/23/22 is the most recent date an event was added.  Did something change around then?
